Repository BuildForSDG/team-029-backend, pull requests merged in 2020-05, with the labels that each got.

#18 feat(auth): setup code structure and implement auth
  .eslintrc.js
  __tests__/app.test.js
  __tests__/unit/controllers/auth/utils.spec.js
  index.js
  migrations/20200509080423-add-users-table.js
  migrations/sqls/20200509080423-add-users-table-down.sql
  migrations/sqls/20200509080423-add-users-table-up.sql
  package.json
  src/app.js
  src/app/controllers/auth/auth.controller.js
  src/app/controllers/auth/utils.js
  src/app/errors/error.codes.js
  src/app/errors/login.error.js
  src/app/errors/login.validation.error.js
  src/app/errors/registration.error.js
  src/app/errors/registration.validation.error.js
  src/app/errors/utils/humanize.errors.js
  src/app/models/user.model.js
  src/app/queries/road.js
  src/app/queries/user.js
  src/app/routes/admin.js
  src/app/routes/auth.js
  src/app/routes/road.js
  src/app/routes/user.js
  src/app/routes/warden.js
  src/app/scripts/create.first.admin.js
  src/app/services/user.service.js
  src/app/utils/database.js
  src/app/utils/validator.js
  src/config/constants.js
  src/config/environment/development.js
  src/config/environment/production.js
  src/config/environment/test.js
  src/config/express.js
  src/config/index.js
  src/config/logger.js
  src/index.js
Labels: auth

#23 Setup heroku pipeline
  app.json
  yarn.lock
Labels: Setup

#42 accidents table
  .env.sample
  migrations/20200522104020-add-accidents.js
  migrations/sqls/20200522104020-add-accidents-down.sql
  migrations/sqls/20200522104020-add-accidents-up.sql
Labels: Completed, In Review, Setup

#45 update app.properties with project and tea…
  app.properties
Labels: Completed, In Review
